### ISSUE TITLE
Load and save detailed history

### ISSUE THREAD

**Issue by Marc-Lorenz** [hcmlab/FaceMeshEditor#68]
- [x] save any step in `fileAnnotationHistory` to API #70 
- [x] if image loaded with API retrieve history #71 
- [x] if saved only save history until visible point (don't save redo)
- [x] start sync with icon on thumbnail #72 
## if loaded with local mediapie and then connected to API
- [x] load history
- [x] overwrite local annotations
